FROM python:3.12.11-alpine3.22

ARG container_user=openg2p
ARG container_user_group=openg2p
ARG container_user_uid=1001
ARG container_user_gid=1001

RUN apk add --no-cache --virtual .build-deps gcc libc-dev linux-headers make
RUN apk add --no-cache bash git gettext libpq-dev

RUN groupadd -g ${container_user_gid} ${container_user_group} \
  && useradd -mN -u ${container_user_uid} -G ${container_user_group} -s /bin/bash ${container_user}

WORKDIR /app

ADD openg2p-registry-celery-beat-producers /app/openg2p-registry-celery-beat-producers
ADD openg2p-registry-bg-tasks-models /app/openg2p-registry-bg-tasks-models 
RUN mv /app/openg2p-registry-celery-workers/main.py /app


RUN python3 -m pip install  \
    git+https://github.com/openg2p/openg2p-fastapi-common@v1.1.1\#subdirectory=openg2p-fastapi-common \
    git+https://github.com/openg2p/openg2p-fastapi-common@v1.1.1\#subdirectory=openg2p-fastapi-auth 

RUN pip install \
  -e /app/openg2p-registry-celery-beat-producers \
  -e /app/openg2p-registry-bg-tasks-models

RUN apk del --no-network .build-deps

USER ${container_user}

ENV PYTHONUNBUFFERED=1

CMD celery -A main.celery_app worker --beat --loglevel=info
